version: '3'
services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:10.1-alpine
    ports:
    - "5432:5432"
